### PR TITLE
Created an Timer using using React and sagu-ui

### PR DESCRIPTION
**Pull request by Shailendra1703**
This time I used sagu-ui to style my Timer, which has pause and restart functionalities.
please check  it  out.
Thank you

### CODE REVIEW

**Review by vczb — APPROVED** [review]
LGTM! well done :)

Can you please squash all the commits in a single one?

**Comment by Shailendra1703** [comment]
> LGTM! well done :)
> 
> Can you please squash all the commits in a single one?

can you please tell me how can I do that

**Comment by vczb** [comment]
> > LGTM! well done :)
> > Can you please squash all the commits in a single one?
> 
> can you please tell me how can I do that

Exists some different ways to do it; In general, I prefer to use an `interactive rebase`. 

Check this link maybe can help

https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

let me know if you have issues with it

**Comment by Shailendra1703** [comment]
image


My commit history shows only one comment of mine , is it right ?

**Comment by vczb** [comment]
> image
> 
> My commit history shows only one comment of mine , is it right ?

Yes, now you need push with `--force` to update the current PR.

`git push origin branch-name -f`

**Comment by Shailendra1703** [comment]
> > image
> > My commit history shows only one comment of mine , is it right ?
> 
> Yes, now you need push with `--force` to update the current PR.
> 
> `git push origin branch-name -f`

Done👍

**Comment by vczb** [comment]
> > > image
> > > My commit history shows only one comment of mine , is it right ?
> > 
> > 
> > Yes, now you need push with `--force` to update the current PR.
> > `git push origin branch-name -f`
> 
> Done+1

@Shailendra1703 You did something wrong. I can fix it for you later

image

**Comment by Shailendra1703** [comment]
Ohh , sorry for inconvenience   can you tell me what I have to do now.

**Comment by vczb** [comment]
> Ohh , sorry for inconvenience can you tell me what I have to do now.

Sorry I closed by mistake

**Comment by vczb** [comment]
> Ohh , sorry for inconvenience can you tell me what I have to do now.

Open a new PR, with a different branch name ( not main ) and submit again. I closed by mistake

@Shailendra1703

**Comment by vczb** [comment]
Make sure that your new forked branch is aligned with the repository main

**Comment by Shailendra1703** [comment]
okay I'll delete this fork and will create a completely new PR,

**Comment by vczb** [comment]
> 

thanks! looking forward to it! you example is pretty cool

**Pull request closed without merging**
