### PR TITLE
Added example in EXAMPLES.md

### PR DESCRIPTION
**Pull request by yash6318**
Added an  example of a Counter App using sagu-ui. 

Fixes part of #31

### CODE REVIEW

**Comment by yash6318** [comment]
I have no idea about the error... as i have changed just onr file EXAMPLES.md and it's running perfectly fine on CodeSandBox.
Plz suggest the changes(if applicable).

**Comment by vczb** [comment]
> I have no idea about the error... as i have changed just one file EXAMPLES.md and it's running perfectly fine on CodeSandBox. Plz suggest the changes(if applicable).

@yash6318  why you did this changes ?
image

---

send a single commit with only the update on the EXAMPLES.md file

**Comment by yash6318** [comment]
No I have'nt!! Check in the files changed section...only 1 is showing.

**Comment by vczb** [comment]
> No I have'nt!! Check in the files changed section...only 1 is showing.
> 
> It's showing `Unchanged files with check annotations` . I have no idea about it! . Plz suggest.

You are right, strange build error. Please squash both commits in a single one. Then submit a new PR with a different branch name ( not main )

Feel free to close this one after the new one

**Comment by vczb** [comment]
hi @yash6318 don't forget to open a new PR in a different branch

**Pull request closed without merging**
