### PR TITLE
added an example in EXAMPLES.md

### PR DESCRIPTION
**Pull request by sai-karthik-p**
Added a new Product Cards Listing example in EXAMPLES.md

It contributes to #31

### CODE REVIEW

**Review by vczb — APPROVED** [review]
LGTM! really cool your example. 

Your PR has a conflict do you know how to fix it?

**Comment by sai-karthik-p** [comment]
Thanks, @vczb! 
I have fixed the conflict.

**Comment by vczb** [comment]
> Thanks, @vczb! I have fixed the conflict.

thanks a lot, can you please squash the both commits in a single one ?

image

**Comment by sai-karthik-p** [comment]
I have squashed both commits in a single one.

**Review by vczb — APPROVED** [review]
LGTM

**Pull request merged**
